DcmCode/Code V.03/Dcm/Models/Project.cs
using Dcm.EntityModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Dcm.Models
{
    public class Project
    {
        [Required]
        public string RecordId { get; set; }
        public string MenuId { get; set; }

        [Required(ErrorMessage = "Project Name is required")]
        public string project_name { get; set; }

        public string project_type_id { get; set; }

        public string kurum_id { get; set; }
        public string birey_id { get; set; }

        public string isveren_mobil_phone { get; set; }
       
        public string note { get; set; }
        public string project_description { get; set; }

        public bool is_active { get; set; }

        public string FromDeleteButton { get; set; }

        public List<crm_kurumlar> activeKurumlar { get; set; }

        public List<crm_bireyler> activeBireyler { get; set; }

        public List<crm_bireyler_kurumlar_v> activeBireylerKurumlar { get; set; }

        public string statik { get; set; }
        public string mekanik { get; set; }

        public string elektrik { get; set; }
        public string harita { get; set; }

        public string yapi_denetim { get; set; }

        public string proje_metrekare { get; set; }

        public string birey_kurum_id { get; set; }

        public List<ref_crm_project_types> projectTypes { get; set; }

        public List<gnl_users> activeUsers { get; set; }

         


    }
}

DcmCode/Code V.03/Dcm/Controllers/CrmController.cs
using Dcm.Models;
using Dcm.Source;
using Gunluk.EntityModels;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dcm.EntityModels;
using BaseDB;
using Dcm.Filters;
using System.Web.Script.Serialization;
using BaseClasses;

namespace Dcm.Controllers
{
    public class CrmController : Controller
    {

        #region Kurum İşlemleri
        [HttpGet]
        [AllowAnonymous]
        [SessionCheckAttribute]
        public ActionResult Kurumlar(string RecordId,string MenuId )
        {
            CrmRepository crmDB = RepositoryManager.GetRepository<CrmRepository>();
            Kurum model = new Kurum();

            #region Ortak Set Edilecek Değerler 
            MenuId = GlobalHelper.Decrypt(MenuId);
            model.RecordId = RecordId;
            model.MenuId = MenuId;
            SessionContext.Current.ActiveUser.MenuId = MenuId;
            #endregion

            Guid recordId = Guid.Empty;


            if (GlobalHelper.IsGuid(model.RecordId))
            {
                try
                {
                    recordId = Guid.Parse(model.RecordId);
                    model = crmDB.BindKurum(model, recordId);
                    ViewBag.ResultMessage = Resources.GlobalResource.transaction_success;
                }
                catch (Exception exp)
                {
                    ViewBag.Success = false;
                    ModelState.AddModelError("Error", exp.Message);
                }
            }

            return View(model);
        }

        [HttpPost]
        [SessionCheckAttribute]
        public ActionResult Kurumlar(Kurum model)
        {
            Guid recordId = Guid.Empty;
            CrmRepository crmDB = RepositoryManager.GetRepository<CrmRepository>();

            #region Ortak Set Edilecek Değerler
            SessionContext.Current.ActiveUser.MenuId = model.MenuId;
            ViewBag.Success = true;
            #endregion

            ModelState.Remove("is_active");

            if (model.FromDeleteButton == "1")
            {
                if (GlobalHelper.IsGuid(model.RecordId))
                {
                    crmDB.DeleteKurum(model, Guid.Parse(model.RecordId));
                    return RedirectToAction("ListPage", "General", new { MenuId =Dcm.Source.GlobalHelper.Encrypt( model.MenuId )});
                }
            }
            else
            {
                if (ModelState.IsValid)
                {
                    if (GlobalHelper.IsGuid(model.RecordId))
                    {
                        recordId = Guid.Parse(model.RecordId);
                        try
                        {
                            model = crmDB.UpdateKurum(model, recordId);
                            ViewBag.ResultMessage = Resources.GlobalResource.transaction_success;
                        }
                        catch (Exception exp)
                        {
                            ViewBag.Success = false;
                            ModelState.AddModelError("Error", exp.Message);
                        }
                    }
                    else
                    {
                        try
                        {
                            crm_kurumlar kurum = new crm_kurumlar();
                            crmDB.AddKurum(kurum, model);
                            model.RecordId = kurum.kurum_id.ToString();
                            ViewBag.ResultMessage = Resources.GlobalResource.transaction_success;
                        }
                        catch (Exception exp)
                        {
                            ViewBag.Success = false;
                            ModelState.AddModelError("Error", exp.Message);
                        }
                    }
                }
                else
                {
                    ViewBag.Success = false;
                }
            }

            return View(model);
        }
        #endregion

        #region Birey İşlemleri
        [HttpGet]
        [AllowAnonymous]
        [SessionCheckAttribute]
        public ActionResult Bireyler(string RecordId, string MenuId)
        {
            CrmRepository crmDB = RepositoryManager.GetRepository<CrmRepository>();
            Birey model = new Birey();

            #region Ortak Set Edilecek Değerler
            MenuId = GlobalHelper.Decrypt(MenuId);
            model.RecordId = RecordId;
            model.MenuId = MenuId;
            SessionContext.Current.ActiveUser.MenuId = MenuId;
            #endregion

            Guid recordId = Guid.Empty;

            model.activeKurumlar = crmDB.GetKurumList();
            

            if (GlobalHelper.IsGuid(model.RecordId))
            {
                try
                {
                    recordId = Guid.Parse(model.RecordId);
                    model = crmDB.BindBirey(model, recordId);
                    if (model.calistigi_kurum_id != null && GlobalHelper.IsGuidOrEmpty(model.calistigi_kurum_id))
                        model.calistigi_kurum_id = model.calistigi_kurum_id.ToString();
                    ViewBag.ResultMessage = Resources.GlobalResource.transaction_success;
                }
                catch (Exception exp)
                {
                    ViewBag.Success = false;
                    ModelState.AddModelError("Error", exp.Message);
                }
            }

            return View(model);
        }

        [HttpPost]
        [SessionCheckAttribute]
        public ActionResult Bireyler(Birey model)
        {
            Guid recordId = Guid.Empty;
            CrmRepository crmDB = RepositoryManager.GetRepository<CrmRepository>();

            #region Ortak Set Edilecek Değerler
            SessionContext.Current.ActiveUser.MenuId = model.MenuId;
            ViewBag.Success = true;
            #endregion

            model.activeKurumlar = crmDB.GetKurumList();
            
            ModelState.Remove("is_active");

            if (model.FromDeleteButton == "1")
            {
                if (GlobalHelper.IsGuid(model.RecordId))
                {
                    crmDB.DeleteBirey(model, Guid.Parse(model.RecordId));
                    return RedirectToAction("ListPage", "General", new { MenuId = Dcm.Source.GlobalHelper.Encrypt(model.MenuId) });
                }
            }
            else
            {
                if (ModelState.IsValid)
                {
                    if (GlobalHelper.IsGuid(model.RecordId))
                    {
                        recordId = Guid.Parse(model.RecordId);
                        try
                        {
                            model = crmDB.UpdateBirey(model, recordId);

                            if (model.calistigi_kurum_id != null && GlobalHelper.IsGuidOrEmpty(model.calistigi_kurum_id))
                                model.calistigi_kurum_id = model.calistigi_kurum_id.ToString();
                            
                            ViewBag.ResultMessage = Resources.GlobalResource.transaction_success;
                        }
                        catch (Exception exp)
                        {
                            ViewBag.Success = false;
                            ModelState.AddModelError("Error", exp.Message);
                        }
                    }
                    else
                    {
                        try
                        {
                            crm_bireyler birey = new crm_bireyler();
                            crmDB.AddBirey(birey, model);
                            model.RecordId = birey.birey_id.ToString();
                            if (birey.calistigi_kurum_id != null)
                                model.calistigi_kurum_id = birey.calistigi_kurum_id.ToString();

                            ViewBag.ResultMessage = Resources.GlobalResource.transaction_success;
                        }
                        catch (Exception exp)
                        {
                            ViewBag.Success = false;
                            ModelState.AddModelError("Error", exp.Message);
                        }
                    }
                }
                else
                {
                    ViewBag.Success = false;
                }
            }

            return View(model);
        }
        #endregion

        #region Proje İşlemleri
        [HttpGet]
        [AllowAnonymous]
        [SessionCheckAttribute]
        public ActionResult Projects(string RecordId, string MenuId)
        {
            CrmRepository crmDB = RepositoryManager.GetRepository<CrmRepository>();
            GenelRepository gnlDB = RepositoryManager.GetRepository<GenelRepository>();

            Project model = new Project();

            #region Ortak Set Edilecek Değerler
            MenuId = GlobalHelper.Decrypt(MenuId);
            model.RecordId = RecordId;
            model.MenuId = MenuId;
            SessionContext.Current.ActiveUser.MenuId = MenuId;
            #endregion

            Guid recordId = Guid.Empty;

            model.activeKurumlar = crmDB.GetKurumList();
            model.activeBireyler = crmDB.GetBireyList();
            model.activeBireylerKurumlar = crmDB.GetBireyKurumList();
            model.activeUsers = gnlDB.GetActiveUsers();
            model.projectTypes = crmDB.GetProjectTypeList();

            model.kurum_id = Guid.Empty.ToString();
            model.birey_id = Guid.Empty.ToString();
            model.project_type_id = "1";

            if (GlobalHelper.IsGuid(model.RecordId))
            {
                try
                {
                    recordId = Guid.Parse(model.RecordId);
                    model = crmDB.BindProject(model, recordId);
                    
                    if (model.birey_id != null && GlobalHelper.IsGuidOrEmpty(model.birey_id))
                        model.birey_id = model.birey_id.ToString();

DcmCode/Code V.03/Dcm/Views/Crm/Bireyler.cshtml
@model Dcm.Models.Birey

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Kurumlar";
}

<link rel='stylesheet' type='text/css' href='~/assets/plugins/datatables/dataTables.css' />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/codeprettifier/prettify.css' />
<link rel='stylesheet' type='text/css' href='~/assets/plugins/form-toggle/toggles.css' />
@using (Html.BeginForm("Bireyler", "Crm", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data", data_validate = "parsley", novalidate = "", id = "validate-form" }))
{
    <input type="hidden" name="RecordId" id="RecordId" value="@Model.RecordId" />
    <input type="hidden" name="MenuId" id="MenuId" value="@Model.MenuId" />
    <div id='wrap'>
        <div id="page-heading" style="
    margin-top: -15px;
">

            <h3>Birey Bilgileri</h3>

            <div class="options">
                <div class="btn-toolbar">
                    <a href="@(Url.Action("ListPage", "General") + "?MenuId=" + Dcm.Source.GlobalHelper.Encrypt(Model.MenuId))" class="btn btn-default"><i class="fa fa-list"></i><span style="padding-left:10px">Return List</span></a>
                </div>
            </div>

        </div>


        <div class="container">
            <div id="message_div" class="alert alert-info" style="display:none;vertical-align:top">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary()
                @ViewBag.ResultMessage
                <button type="button" class="close" data-dismiss="alert">&times;</button>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h4>Detail</h4>

                        </div>
                        <div class="panel-body">

                            <div class="form-group">
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 form-validate">
                                    <label class="control-label">@Dcm.Source.GlobalHelper.GetGlobalResource("ad")</label>
                                </div>

                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 form-validate">
                                    <input type="text" class="form-control" name="ad" required="required" id="ad" value="@Model.ad" autocomplete="off" placeholder="@Dcm.Source.GlobalHelper.GetGlobalResource("ad")">
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 form-validate">
                                    <p><label class="control-label">@Dcm.Source.GlobalHelper.GetGlobalResource("soyad")</label></p>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 form-validate">
                                    <p><input type="text" name="soyad" id="soyad" required="required" value="@Model.soyad" class="form-control" autocomplete="off" placeholder="@Dcm.Source.GlobalHelper.GetGlobalResource("soyad")"></p>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 form-validate">
                                    <label class="control-label">@Dcm.Source.GlobalHelper.GetGlobalResource("eposta_adresi")</label>
                                </div>

                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 form-validate">
                                    <input type="text" class="form-control" name="eposta_adresi"  data-type="email" value="@Model.eposta_adresi" id="eposta_adresi" autocomplete="off" placeholder="@Dcm.Source.GlobalHelper.GetGlobalResource("eposta_adresi")">
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 form-validate">
                                    <p><label class="control-label">@Dcm.Source.GlobalHelper.GetGlobalResource("web_sitesi")</label></p>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 form-validate">
                                    <input type="text" class="form-control" name="web_sitesi" value="@Model.web_sitesi" id="web_sitesi" autocomplete="off" placeholder="@Dcm.Source.GlobalHelper.GetGlobalResource("web_sitesi")">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 form-validate">
                                    <label class="control-label">@Dcm.Source.GlobalHelper.GetGlobalResource("mobile_phone")</label>
                                </div>

                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 form-validate">
                                    <input type="text" class="form-control mask" data-type="phone" required="required" name="mobile_phone" id="mobile_phone" data-inputmask="'mask':'(999) 999-9999'" value="@Model.mobile_phone" autocomplete="off" placeholder="@Dcm.Source.GlobalHelper.GetGlobalResource("mobile_phone")">
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 form-validate">
                                    <label class="control-label">@Dcm.Source.GlobalHelper.GetGlobalResource("telefon1")</label>
                                </div>

                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 form-validate">
                                    <input type="text" class="form-control mask" data-type="phone"  name="telefonu_1" id="telefonu_1" data-inputmask="'mask':'(999) 999-9999'" value="@Model.telefonu_1" autocomplete="off" placeholder="@Dcm.Source.GlobalHelper.GetGlobalResource("telefon1")">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 form-validate">
                                    <p><label class="control-label">@Dcm.Source.GlobalHelper.GetGlobalResource("faks1")</label></p>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 form-validate">
                                    <p><input type="text" name="faksi_1" id="faksi_1" value="@Model.faksi_1" class="form-control mask" data-inputmask="'mask':'(999) 999-9999'" data-type="phone" autocomplete="off" placeholder="@Dcm.Source.GlobalHelper.GetGlobalResource("faks1")"></p>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 form-validate">
                                    <p><label class="control-label">@Dcm.Source.GlobalHelper.GetGlobalResource("calistigi_kurum")</label></p>
                                </div>

                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 form-validate">
                                    @if (Model.activeKurumlar != null && Model.activeKurumlar.Count > 0)
                                    {
                                        <select class="form-control" style="width:100%" name="calistigi_kurum_id" id="ddlRoles" >
                                            <option value="@Guid.Empty" @(Model.calistigi_kurum_id == Guid.Empty.ToString() ? "selected" : "")>Seçiniz</option>
                                            @foreach (var item in Model.activeKurumlar)
                                            {
                                                <option value="@item.kurum_id" @(Model.calistigi_kurum_id == item.kurum_id.ToString() ? "selected" : "")>@item.ticari_unvani</option>
                                            }
                                        </select>
                                    }
                                </div>
                               
                            </div>
                            
                            <div class="form-group">
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 form-validate">
                                    <label class="control-label">@Dcm.Source.GlobalHelper.GetGlobalResource("address")</label>
                                </div>
                                <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12 form-validate">
                                    <textarea name="adres" id="adres" required="required" cols="50" rows="4" class="form-control">@Model.adres</textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 form-validate">
                                    <label class="control-label">@Dcm.Source.GlobalHelper.GetGlobalResource("note")</label>
                                </div>
                                <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12 form-validate">
                                    <textarea name="note" id="note" cols="50" rows="4" class="form-control">@Model.note</textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 form-validate">
                                    <label class="control-label">@Dcm.Source.GlobalHelper.GetGlobalResource("isactive")</label>
                                </div>
                                <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                                    <input type="checkbox" id="chk_is_active" name="chk_is_active">
                                    <input type="hidden" id="is_active" name="is_active">
                                </div>
                            </div>

                        </div>
                        <div class="panel-footer">
                            <div class="row">
                                <div class="col-sm-6 col-sm-offset-3">
                                    <div class="btn-toolbar">
                                        @if(Dcm.Source.GlobalHelper.IsAuthorized(Model.MenuId,"update_right",BaseDB.SessionContext.Current.ActiveUser.UserUid.ToString()))
                                        {
                                        <input type="submit" class="btn-primary btn" value="Save" onclick="Update()" />
                                        }

                                        @if (Model.RecordId != "" && Model.RecordId != Guid.Empty.ToString() && Dcm.Source.GlobalHelper.IsAuthorized(Model.MenuId, "delete_right", BaseDB.SessionContext.Current.ActiveUser.UserUid.ToString()))
                                        {
                                        <input type="button" style="margin-left:50px" class="btn-danger btn" value="Delete" onclick="Delete()" />
                                        }
                                        @*<button class="btn-default btn">Cancel</button>*@
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



        </div><!-- container -->
    </div>

    <input type="hidden" id="FromDeleteButton" name="FromDeleteButton" />
}

<style>
    .table-bordered > tbody > tr > td {
        padding: 5px;
        line-height: 1.428571429;
        vertical-align: top;
        border-top: 1px solid #e6e7e8;
    }

    #wrap > .container {
        padding: 10px;
    }

    #wrap {
        margin-top: 0px;
    }
</style>
<script type='text/javascript' src='~/assets/plugins/datatables/jquery.dataTables.min.js'></script>
<script type='text/javascript' src='~/assets/plugins/datatables/dataTables.bootstrap.js'></script>

<script>
    $(document).ready(function () {
      

        if ('@Model.is_active' == 'True' || '@Model.is_active' == 'true' || '@Model.is_active' == 'TRUE') {
            $("#chk_is_active").prop('checked', true);
        }


    });

    function Update() {
        if ($("#chk_is_active").prop('checked') == true) {
            $("#is_active").val("true");
        }

        var isValid = $('#validate-form').parsley().validate();

        if (!isValid) {
            $('#message_div').hide()
        }

    }

    function Delete() {

        bootbox.confirm('@Resources.GlobalResource.are_you_sure_to_delete', function (result) {
            if (result) {
                $("#FromDeleteButton").val("1");
                $("#validate-form").parsley().destroy();
                $("#validate-form").submit();
            }
        });
        
    }
</script>